# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
